import { User } from '@/models/User';
import { connectDb } from '@/services/db';
import { NextRequest, NextResponse } from 'next/server';
import { isLoggedIn } from '../helpers/auth';
import { Note } from '@/models/Note';
import { validate } from '@/validation/validator';
import { noteSchema } from '@/validation/validationSchemas';
import { filterPublicNote, filterPublicNotes } from '../helpers/note';
import { encrypt } from '@/services/cipher';

connectDb();

// GET /api/notes
// get all notes
export async function GET(request: NextRequest) {
  try {
    // check if user is logged in
    // accessible only for authenticated users
    const userId = await isLoggedIn(request);
    if (!userId) {
      return NextResponse.json(
        { success: false, message: 'Unauthorized' },
        { status: 401 }
      );
    }

    // get all notes for user
    const { notes } = await User.findById(userId);

    return NextResponse.json(
      {
        success: true,
        message: `Found ${notes.length} note(s)`,
        notes: filterPublicNotes(notes),
      },
      { status: 200 }
    );
  } catch (error: any) {
    console.log(error);
    return NextResponse.json(
      { success: false, message: 'Something went wrong' },
      { status: 500 }
    );
  }
}

// POST /api/notes
// add new note
export async function POST(request: NextRequest) {
  try {
    // check if user is logged in
    // accessible only for authenticated users
    const userId = await isLoggedIn(request);
    if (!userId) {
      return NextResponse.json(
        { success: false, message: 'Unauthorized' },
        { status: 401 }
      );
    }

    // note data from user
    const reqBody = await request.json();
    const { title, body, locked, notePassword, confirmNotePassword } = reqBody;

    // validate note data
    const { success, errorMessage } = validate(noteSchema, {
      title,
      body,
      locked,
      notePassword,
      confirmNotePassword,
    });

    if (!success) {
      return NextResponse.json(
        { success: false, message: errorMessage },
        { status: 400 }
      );
    }

    // get logged in user
    const user = await User.findById(userId);

    // create new note
    const note = new Note({ title, body, locked });

    // encrypt data for locked note
    if (locked) {
      const { success, message, encrypted, iv } = encrypt(
        note.body,
        notePassword
      );

      if (!success) {
        return NextResponse.json(
          { success: false, message: message },
          { status: 400 }
        );
      }

      // store encrypted text and iv generated by encryption
      note.body = encrypted;
      note.iv = iv;
    }

    // add new note and save
    user.notes.push(note);
    await user.save();

    return NextResponse.json(
      { success: true, message: 'Note created', note: filterPublicNote(note) },
      { status: 201 }
    );
  } catch (error: any) {
    console.log(error);
    return NextResponse.json(
      { success: false, message: 'Something went wrong' },
      { status: 500 }
    );
  }
}

export const dynamic = 'force-dynamic';
